### ISSUE TITLE
Crashes Perhaps Something to do with React

### ISSUE THREAD

**Issue by elliothimmelfarb** [mnbroatch/react-template#1]
I have submitted a pull request with what I believe to be simply fixing a linting error. It is crashing for me with an error too long for iterm to keep in memory. 

They all have React in the name though so I supposed it could be React failing.

I have cloned and npm installed. It was not working but I fixed a linting error.

Has anyone else run into a crash like this?

**Comment by elliothimmelfarb** [comment]
Here is the error from the npm-debug log:

error Darwin 15.5.0
18 error argv "/Users/elliothimmelfarb/.nvm/versions/node/v6.2.1/bin/node" "/Users/elliothimmelfarb/.nvm/versions/node/v6.2.1/bin/npm" "start"
19 error node v6.2.1
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error react-template@1.0.0 start: `NODE_ENV=development npm-run-all --parallel open:src lint:watch`
22 error Exit status 1
23 error Failed at the react-template@1.0.0 start script 'NODE_ENV=development npm-run-all --parallel open:src lint:watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-template package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=development npm-run-all --parallel open:src lint:watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-template
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-template
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by elliothimmelfarb** [comment]
BTW this is a really sick template. 

Really love reading this code.

**Comment by elliothimmelfarb** [comment]
It appears I am having git trouble. I believe that /tools/db.thing.js should be renamed to Thing.js as it is referenced in /tools/api/things.js.

**Comment by mnbroatch** [comment]
Oh man, when I cloned it down there were about a million module not found errors... 

A few things were wrong. First, you need an empty string as the first resolve filetype in the webpack array. That was the main problem. Second, git doesn't recognize case-only renames without doing 'git mv'.

Also, I changed webpack to use the right sourcemaps and to explicitly include the src folder, which reduced initial dev build from 40+ seconds to < 20. Nice.
